---
- name: Install bridge utillites
  yum:
    name: bridge-utils
    state: present

- name: adding bridge parameters to kvm.conf
  lineinfile:
    path: /etc/sysctl.d/kvm.conf
    line: net.bridge.bridge-nf-call-ip6tables = 1
    insertafter: EOF
    state: present
    create: yes

- name: Add bridge to kvm.conf
  lineinfile:
    path: /etc/sysctl.d/kvm.conf
    line: net.bridge.bridge-nf-call-iptables = 1
    insertafter: EOF
    state: present

- name: add parameters to kvm.conf
  lineinfile:
    path: /etc/sysctl.d/kvm.conf
    line: net.ipv4.ip_forward = 1
    insertafter: EOF
    state: present

- name: add modules to load kvm.conf
  lineinfile:
    path: /etc/modules-load.d/kvm.conf
    line: overlay
    insertafter: EOF
    state: present
    create: yes

- name: add modules to load kvm.conf
  lineinfile:
    path: /etc/modules-load.d/kvm.conf
    line: br_netfilter
    insertafter: EOF
    state: present

- name: checking for br_netfilter
  modprobe:
    name: br_netfilter
    state: present

- name: checking for overlay
  modprobe:
    name: overlay
    state: present
